### ISSUE TITLE
Cannot update to Version 1.9.9 

### ISSUE THREAD

**Issue by fjsosa** [joomlaboat/custom-tables#11]
**Describe the bug**
The plugin is not updated correctly

**To Reproduce**
1. Go to 'Extensions/Manage/Update.'
2. You see that version 1.9.9 is available for the pugin
2. Click on 'Update'
3. The update finish aparently Correct
4. Go to the custom table administration page
5. the Version is still 1.9.8 (not updated

**Expected behavior**
The Version 1.9.8 should be updated to 1.9.9 if you update the plugin

**Additional context**

Database Type| mysql
DB Version | 5.6.49-cll-lve
DB Encoding | latin1_swedish_ci
DB Connection Encoding | utf8mb4_general_ci
PHP | 7.3.21
Web Server | Apache
PHP Interface | litespeed
Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by joomlaboat** [comment]
Thank you.
New file wasn't uploaded.
I uploaded the latest 1.9.9 files - tested. Fixed.
