### ISSUE TITLE
v2.4.1 - Unknown column 'ordering' in 'field list'

### ISSUE THREAD

**Issue by Krautix** [joomlaboat/custom-tables#13]
Hi!
Made a first/clean install (non pro) on Joomla 3.10.2. Install and creation of database schema went fine.

New table dialog throws error "Unknown column 'ordering' in 'field list'"
New category dialog throws the same error.

**Comment by joomlaboat** [comment]
Thank you Krautix, the issue is fixed. Please install 2.4.2 version.
