### ISSUE TITLE
v.2.4.3: Changeing a field throws error "Unknown column 'version' in 'field list'"

### ISSUE THREAD

**Issue by Krautix** [joomlaboat/custom-tables#15]
Hi!
In v.2.4.3, changeing a field of a table throws error "Unknown column 'version' in 'field list'"

**Comment by joomlaboat** [comment]
Changing the field name or field type?

**Comment by Krautix** [comment]
It is now uninstalled. But I guess you can try yourself. Just go into a field and try to change something. I alway got the error.
I uninstalled now because it was buggy elsewhere again. I think it was the "last change date" that was set to 1970...

**Comment by Krautix** [comment]
I can try again in a few hours. Have you also updated the download package on the website?

**Comment by joomlaboat** [comment]
not yet

**Comment by joomlaboat** [comment]
Fixed.
