### ISSUE TITLE
Image Uploader Query v2.5.4

### ISSUE THREAD

**Issue by SandPeopleChoir** [joomlaboat/custom-tables#16]
Hi,

I've created a table and I can't upload images. I'm using PHP 7.4 and Joomla 4 on XAMPP localhost. I've set up the field as follows:

![image](https://user-images.githubusercontent.com/94364785/141772667-c417f32c-d397-4cc8-9bc2-9bd080d9b2ea.png)

When going into tables -> <mytable> -> Records, I get this without the upload function:

![image](https://user-images.githubusercontent.com/94364785/141772808-8c2a94b4-7813-4c9a-a38a-273f0ec4e9ce.png)

I'm sure it's config error by me - anything you can help with please?

Thanks.

**Comment by joomlaboat** [comment]
Hello,

Try to change Folder to "flags" without "images/"

**Comment by joomlaboat** [comment]
Hello SandPeopleChoir, please update to 2.9.0 version. The issue must be fixed already.
