### ISSUE TITLE
Table Join - Pre-populate field names

### ISSUE THREAD

**Issue by felixkat** [joomlaboat/custom-tables#23]
For table joins.

Once a table has been selected make "Field Name" a drop down list of fields from the table selected.

![image](https://user-images.githubusercontent.com/1116451/170283745-eb95757e-be36-40d3-9533-3abedc2e87fd.png)

**Comment by joomlaboat** [comment]
That will be useful.

**Comment by joomlaboat** [comment]
Ready.

![imagen](https://user-images.githubusercontent.com/8064340/183834751-59080027-21af-4d1d-8633-6010bc4ec292.png)

2.8.6 (2022-08-10) - Back-end: Both field types Table Join and Multi Table Join are improved - field name select box added. Field selection also works in the Layout Editor, when editing tag parameters.

It may require to clean browser temporary files.

Please update Custom tables.
