### ISSUE TITLE
Allowed Field Types in File field

### ISSUE THREAD

**Issue by swennomaak** [joomlaboat/custom-tables#24]
Allowed field types are now 

doc docx xls xlsx pdf pages ppt pptx
I changed it to:
txt rtf doc docx xls xlsx pdf pages ppt pptx odt
all work except rtf
rtf gives a not allowed message

Is it possible to change that?
thanks in advance
regards
Menno

**Comment by joomlaboat** [comment]
Hello Menno,

RTF file type is added.

https://github.com/joomlaboat/custom-tables/commit/051d913886c810f0427b2a9f5c6607de025e79c5

Please try 2.8.2 version.
