### ISSUE TITLE
Information in WIKI on Image field and Image Gallery field

### ISSUE THREAD

**Issue by swennomaak** [joomlaboat/custom-tables#25]
dear Ivan

the more I use Custom Tables the more I Like it. 
I think it is growing towards a great and important tool that partly can replace Fabrik. 

there is missing some information in the description in the wiki for the Images fields.
Like on 'Background' (no idea what to fill there) and what different option there are in the layouts for these field types.
Van you give me some help
thanks in advance
Menno

**Comment by swennomaak** [comment]
By experimenting I found it for the Image field. So that is solved

But my next thing is the Image Gallery field. 
In the Edit Form only a gray line appears with < at the beginning and > at the end.

Is this field type still under construction, or is there a bug or am I doing wrong something?

**Comment by joomlaboat** [comment]
Hello Menno,

The background is the RGB color, FFFFFF for example, to fill up the space if the proportions of the image is different than selected dimensions.

**Comment by joomlaboat** [comment]
Can you please show the screen-shot of the field setting and the front-end result?

**Comment by swennomaak** [comment]
send them by email, hope you got them

**Comment by joomlaboat** [comment]
Hello, I didn't receive the screen-shots.
Please send to support@joomlaboat.com

**Comment by swennomaak** [comment]
sent it to support@joomlaboat.com

thanks

**Comment by joomlaboat** [comment]
![image](https://user-images.githubusercontent.com/8064340/181033730-6bb36d01-5d67-4f2f-84e5-da600e334b17.png)

Image size name should not include quotes.
Background color - also no quotes and no hash tag.
Please try the folder path without leading slash character - like this: images/jpeg

**Comment by joomlaboat** [comment]
Also to edit this type of field you need to have the record already saved. It requires record id to link to.

There is a {{ html.toolbar }} tag in Catalog layout, this tag renders edit,delete,publish etc buttons, it can also may render a button to open the Image Gallery or File Box editor.

Example: {{ html.toolbar("edit","publish","gallery","filebox") }}

![image](https://user-images.githubusercontent.com/8064340/181035688-b22a9539-ca8b-4bc1-bd6a-33cfe32adb80.png)

**Comment by swennomaak** [comment]
unfortunately the Image Gallery field doesn't appear in the layouts.

**Comment by joomlaboat** [comment]
Try this:

{{ html.toolbar("gallery") }}

can you post a screen-shot of what you see here?

**Comment by swennomaak** [comment]
I placed it in the list layout. There is then a nice icon and the tooltip gives the name of the field.
But on the page I get the error message 'danger  Not authorized'.

**Comment by swennomaak** [comment]
sometimes I have the feeling that the Pro capabilities are not fully enabled.

**Comment by joomlaboat** [comment]
![image](https://user-images.githubusercontent.com/8064340/181405048-de98a0a7-0e26-44a5-baee-99a256489e7e.png)

Is it possible that the Edit user group is not the one of the user you login in to the front-end?

I updated Image Galler and File Box field types. I found some bugs there.

https://github.com/joomlaboat/custom-tables

**Comment by joomlaboat** [comment]
> sometimes I have the feeling that the Pro capabilities are not fully enabled.

The Pro version functionality is less tested because more people use the Free version. Also The Pro version has almost a double more features.

**Comment by swennomaak** [comment]
Thanks for all improvements Ivan
I was not able to try them all but i will continue to work with Custom Tables and explore it to the very limits. 
If all goes well and I achieve what I need, for sure that I will promote your creation. It might be a good replacement for many of the Fabrik users.

For now I have difficulties in saving all rich text formatting in a Text Area.
The editor is there an I can work with it as aspected but one saving all formatting is stripped.

**Comment by joomlaboat** [comment]
The output of the Text Area value is stripped if you limit it by number of words or characters.

{{ textfield("chars",100) }} - Stripped.

{{ textfield }} - As it is.

But CSS and Script will be stripped anyway by the Joomla itself.

**Comment by swennomaak** [comment]
Thank you Ivan

this all is really helpful. I can do almost everything I need to do now. 
The more I understand how the Custom Tables is meant to work the more I like it. 
I will add a positive review in the JED and I will e a Patron (patreon) for some time.

Probably I will ask question if I am not able to find my way through Custom Tables just by myself. 
For now I am fine. You can close this.

There is one thing; on (some?> Edit Forms there is a message 'Table not selected'
thanks
Menno

**Comment by joomlaboat** [comment]
Hello Meeno,

The 'Table not selected' is fixed in 2.8.5.

Also few other things are fixed:

Image field type parameters in the back-end fixed (joomla 3.x).
{{ table.title }} tag bag fixed (The 'Table not selected').
Alpha-numerical field names can be used in filters.
XML field types and tag meta data is loaded using PHP.
Pagination for J4 improved.
Pagination arrows option added (Text or Icons) {{ pagination(true) }}.
