### ISSUE TITLE
Add ability to join "standard" tables

### ISSUE THREAD

**Issue by mc-cm** [joomlaboat/custom-tables#26]
Hello!
I'd need to create a directory of locations and "connect" contact information to it. 
Custom tables will do the location directory quite fine! Thanks for that.
But all the contact entries I already have in my com_contact tables / component. 
So, it would be a perfect thing if I just could join data from com_contacts to the custom table location directory.
As detail: some contacts have different roles at different locations; so I'd need several fields to add contact data, for example: 

- location 1 manager -> contact 1
- location 1 cleaning person -> contact 2

- location 2 manager -> contact 2
- location 2 cleaning person -> contact 1
- etc.

Maybe I'm not die only one who would find it helpful to have access to other tables (articles / contacts).
Thanks a lot!

**Comment by joomlaboat** [comment]
Hello,

![image](https://user-images.githubusercontent.com/8064340/180871210-2728aa4a-2442-4872-ba9d-bbe5a92cfaba.png)

Its very easy, just select Third-party table in Advanced tab, and type the name of the Primary Key field.
You will be able to access all fields and records of that table in the same way like with Custom Tables: {{ name }}, {{ position }}

Regards,
Ivan
