### ISSUE TITLE
Ordering field not working

### ISSUE THREAD

**Issue by swennomaak** [joomlaboat/custom-tables#28]
The new features for the Ordering field look very nice.
But it is not working yet.
The line of three points is there, the cross is there when you move your cursor over it. But there is no way to move the records to another position. 
I have found this in Firefox on Windows 10 and 11 and in Edge Windows 11.

The new version of the information of the Ordering field suggests that the the Layout Auto Creator will place the field at the start of the row. That does not happen. I can of-course change that manually. 

Latest version of Joomla 4.1 and Custom Tables (2.8.9)

thanks in advance
regards Menno

**Comment by mennoswaak** [comment]
Thanks Ivan. It really works and it works well. Great feature!
