### ISSUE TITLE
Problem with edit and save a record with a field of the Imgae File type

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#29]
**Describe the bug**
When I add a record with a Image File all work well when I save it.
But when I try to edit the same record I see a thumbnail of image I entered before but there is no file name or so.
When I then try to Save or try to Save and Close the record a message shows up saying that a filename is required. 
Cancel is the only way out.
It seems that some value is missing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 104.0.2
![CT-Screen-2022-09-15_00-39-30](https://user-images.githubusercontent.com/102488514/190277325-5ab81ac8-65f9-4828-b4fd-d570a3299583.jpg)

**Comment by joomlaboat** [comment]
Hello Meeno,

Please try 2.9.0 version, I think I already fixed it. Just tested it again.

**Comment by mennoswaak** [comment]
Hi Ivan, that is the version I am using

**Comment by joomlaboat** [comment]
I see, its fixed in Joomla 4.x but not fixed in Joomla 3.x. Tried on Joomla 3.x and I see the problem.

**Comment by mennoswaak** [comment]
Here I have Joomla 4..2.2

**Comment by joomlaboat** [comment]
Hello Menno, I uploaded the fix to GitHub.
Please try. The problem was in the inputbox ID.

**Comment by mennoswaak** [comment]
Thanks Ivan, that is much better now. I can work with it. No more error messages and and value are saved.

**Comment by joomlaboat** [comment]
Good.  Happy to hear that.
