### ISSUE TITLE
Filtering on a value of he type integer?

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#30]
Hello

is there a possibility to filter list on some value in one of the fields.
If I add now a a list to a menu item I can filter on values related to user and user field (I do not understand now how its works because of I did not study it).
But what i need is a filter that can come from a field (can be an integer) in order to only present records with a specific value.
I hope this is possible somehow

thanks in advance
Menno

**Comment by joomlaboat** [comment]
Hello Menno,

I just wrote a small article to explain how Filters work:

[https://github.com/joomlaboat/custom-tables/wiki/07.-Filters](https://github.com/joomlaboat/custom-tables/wiki/07.-Filters)

Also you can insert records from any tables to any layout using {{ tables.getrecords() }}

## {{ tables.getrecords() }}

Renders another table records using selected layout.

Parameters

    Catalog Layout

    Filter - Example: price>100

    Order By Field - Example: name desc

    Limit - Max number of records to load. Example: 20

### Example

{{ tables.getrecords("CountriesPage","population>" ~ citypopulation.value,"name",20) }}

where "citypopulation" is the current table field and "CountriesPage" is the layout of another table to get the records from.

Hope it will be helpful.

**Comment by joomlaboat** [comment]
You can use the Menu Item/Filter/Search Parameter

Example:

price>0 and active=1

price<{{ payment.value }}
