### ISSUE TITLE
Image File storing another kind of name

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#33]
**Is your feature request related to a problem? Please describe.**
Image File field produces a filename based on size, date and time or so (groot_20220907222328.jpg).
Such a filename is not easy to find out what it is or what it's original name was.

**Describe the solution you'd like**
For my clients it will be more easy if the original name was kept within the new name or that he can add a new name (or part of a name) that van be used to create the new filename. 
So the result could be something like: groot_appelsandpears.jpg

TIA
menno

**Comment by joomlaboat** [comment]
Try to use File Field type, it preserves the original name.

**Comment by mennoswaak** [comment]
Thanks Ivan,
I already did that, but then there is no resizing. 
And resizing is a very handy tool for what I need.
Maybe I have to learn to program in PHP to add some code that renames the results of the Image File.

**Comment by joomlaboat** [comment]
Hello Menno,

I am adding an option how to save an uploaded file:

![image](https://user-images.githubusercontent.com/8064340/196231266-49586095-5bb8-48df-9a71-88c093538527.png)

**Comment by joomlaboat** [comment]
The As File Name option added to 2.9.4 version.
