### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#36]
when i click the record id in a list of records in a menu item it works fine and opens the correct detail page.
but when there is a filter active clicking on a record's id always opens the same detail page and I think it is the last added record.
what can be the course, is it a bug? 
This is in Joomla 3.20.11  and Custom Tables 2.9.4

**Comment by joomlaboat** [comment]
Thank you Menno,

This is a bug - fixed. Please install the latest update from the GitHub.
The fix will be included to the next release.
