### ISSUE TITLE
sqljoin in dropdown with two fields from the other table?

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#37]
Hello

in a table I have Table Join. Is it possible to make in the dropdown list the value of two fields from the other table visible?
Field one: integer, field two: string and to save only the content of field one.
The part with field one is working very well, but I can't find no way to add the second field.
How to do this?
Tanks in advance.

Best to know: I am making nice applications with Custom Tables. It is very promising. 
kind regards 
menno

**Comment by joomlaboat** [comment]
I will add this option.

It will be a part of the edit parameters {{ fieldname.edit(Params) }}

I would like to see the application you are making.

**Comment by mennoswaak** [comment]
The application I'm making now is an exercise. It contains a lot of personal information and is not suitable for showing. But the next application will be. It is for a non-profit educational organisation. And the main part of the content will come from Custom Tables. I will send you a link when it is ready.

**Comment by joomlaboat** [comment]
Hello Menno, the option to control the dropdown list titles is added to 2.9.8 version.

Example: {{ join.edit("","",[],"myCustomTitle") }}

Where "myCustomTitle" is the layout name to render the titles.

![image](https://user-images.githubusercontent.com/8064340/201432272-190f0b2c-b0de-4eec-a89a-6cc91da9351d.png)

**Comment by mennoswaak** [comment]
Thanks Ivan
it is working
