### ISSUE TITLE
Can the value of the Checkbox (Yes/No) field be displayed with an icon in a list?

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#39]
Hi 

is there a way to have icons in stead of strings (yes / no)  or integer (0 / 1) in a List and maybe also on Detail pages?
 T.I.A.
 menno

**Comment by joomlaboat** [comment]
Hi, try to use the IF statement: {% if fieldname.value == 1 %}<img src="" />{% endif %}

**Comment by joomlaboat** [comment]
{% if fieldname.value == 1 %} icon or image here {% endif %}

**Comment by mennoswaak** [comment]
it is working Ivan   thanks

**Comment by mennoswaak** [comment]
I have another question:  does Custom Tables work on PHP 8.1 ?

**Comment by joomlaboat** [comment]
It doesn't work on PHP 8.1 yet. I am working on it.

**Comment by mennoswaak** [comment]
how long will that take, Ivan, will that be days, weeks or months?
Have you any idea?

**Comment by joomlaboat** [comment]
A day or two, already did, few more tests and done.

**Comment by joomlaboat** [comment]
PHP 8.1 compatibility is ready. Please update to 2.9.9 version.
