### ISSUE TITLE
html.pagination not working in a list with a record.jointable

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#41]
Hello
html.pagination work well in a List directly in a menu option
but not in this situation where a list is embedded in a Details page through a record,jointable 
Is there a easy solution? This is not very important

**Comment by joomlaboat** [comment]
Hello Menno,

The "Paginaton" depends on URL query parameter "start" and it can only be used with the Custom Tables - Records Menu Item.
