### ISSUE TITLE
Newly added Ordering field not working

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#48]
An Ordering field in a tables I made some time ago is still working, but when I add an Ordering Field to another tables it is there but not active.
As far I can see all configuration is the same in the old and in the newer tables.

Is this a bug?

Newest Custom Tables, 
Joomla 4.2.6
Windows 10 als well on Windows 11
Firefox

**Comment by joomlaboat** [comment]
Hello Menno,

New record ordering field is NULL by default and cannot be reordered. Its a bug.
I found the same about creating new fields, its fixed.

I will fix that bug as well and upload the update.

**Comment by mennoswaak** [comment]
Thank you Ivan
I'll wait for the update before te continue

**Comment by joomlaboat** [comment]
Hello Menno, version 3.0.4 is ready. Please try.

**Comment by mennoswaak** [comment]
Sorry Ivan, stille the same:  nog working....

⁣BlueMail voor Android downloaden ​

Op 26 jan. 2023 16:21, om 16:21, JoomlaBoat ***@***.***> schreef:

**Comment by mennoswaak** [comment]
thank you, now it works

**Comment by joomlaboat** [comment]
Good. Happy to hear that.
