### ISSUE TITLE
News Items on Interior

### ISSUE THREAD

**Issue by juliager** [joomlaboat/custom-tables#5]
Alina posted Collections news for David from Panama platform. I told her to unpublish it and create a new item on David platform, 
She did that but unpublishing collections document from panama did not help...david has currently duplicate Collections news, only one is editable and if unpublished, both Collection news items disappear. Either 0 or 2. No other option is given to us.
![image](https://user-images.githubusercontent.com/64045111/82922107-cc253280-9f3e-11ea-8ec5-349d6c9dea20.png)

**Comment by joomlaboat** [comment]
Not Custom Tables related.
