### ISSUE TITLE
Database Scheme

### ISSUE THREAD

**Issue by sup3r93** [joomlaboat/custom-tables#50]
**Describe the bug**
When I click on the "database schema" button the following error appears:

**To Reproduce**
1. Database schema
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/94311785/220107468-ba2df670-798b-4d05-9d05-92c410734330.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Google Chrome 109.0.5414.120
 - Plugin Version: 1.0.2

**Comment by joomlaboat** [comment]
Fixed. Please try the update from GitHub
https://github.com/joomlaboat/custom-tables
