### ISSUE TITLE
Select field

### ISSUE THREAD

**Issue by eestein** [joomlaboat/custom-tables#51]
Hi!
I looked for it, but could not find if it already exists - it looks like it doesn't.
When creating the fields for a table, is it possible to have a select with predefined values?

**Comment by joomlaboat** [comment]
Hi,

There are two options: Table Join field - Create a new table with the list of options and add a field with Table Join type to connect to the table with the list of options.

Another option is the Radio Buttons field type.

**Comment by eestein** [comment]
Thank you!
