### ISSUE TITLE
export/import table

### ISSUE THREAD

**Issue by internet-conception** [joomlaboat/custom-tables#52]
Trying to import a working table to another website  (same sandbox server) and I got this message : 

0 Argument 7 passed to CustomTables\Fields::addField() must be of the type array, string given, called in /volume1/Web/asso/components/com_customtables/libraries/customtables/utilities/importtables.php on line 419

No menu, no layout, no records is imported, only the table and the first field "id"...

**Comment by joomlaboat** [comment]
Hello,

The issue is fixed.  Please download the 3.0.9 version.
