### ISSUE TITLE
menu filter type is a radio

### ISSUE THREAD

**Issue by internet-conception** [joomlaboat/custom-tables#53]
I try to menu filter a list of records based on radio checkbox field.
Is there a specific syntaxt (in the where clause) or is there a bug ?
<img width="1658" alt="Capture d’écran 2023-05-05 à 00 01 26" src="https://user-images.githubusercontent.com/2952654/236339215-c8207cae-27a4-4eb0-b159-5726f1aa4807.png">

**Comment by internet-conception** [comment]
here is the field
<img width="1635" alt="Capture d’écran 2023-05-05 à 00 02 30" src="https://user-images.githubusercontent.com/2952654/236339413-69adf295-88f8-4ce6-a4a5-44208c5bcb23.png">

**Comment by joomlaboat** [comment]
Hello Internet Conception,

Thank you for your feedback.

The issue is fixed (The search by Radio field type wasn't implemented)

Please update to the 3.1.0 version

https://joomlaboat.com/custom-tables

Regards,
Ivan

**Comment by internet-conception** [comment]
Great ! now work perfectly :)
