### ISSUE TITLE
Import field join type

### ISSUE THREAD

**Issue by WvdMersch** [joomlaboat/custom-tables#54]
I am trying to upload a CSV file into a table with several 'field join'-types. Although the value in the column of the CSV-file mathes the value in the joined table, it is not imported.

Is there a way to import a CSV-file and immediately select the right value for 'field join' types?
If not, then I'd like to see this as an option in the future. 

An alternative solution for now is to skip the 'field join' types and fill in those fields manually after the CSV import. However, this can be a very time consuming action.

**Comment by joomlaboat** [comment]
Hello WvdMersch,

It should work with Table Join fields. Maybe the field name does not match or encoding table problem.
Can you post the table structure and the part of the CSV file here? Or send it to support@joomlaboat.com

**Comment by WvdMersch** [comment]
Yes, you are right. The problem was already solved yesterday. I tried to close this issue but that didn't work
