### ISSUE TITLE
Import CSV - Errors, Field Type Date, String and Checkbox 

### ISSUE THREAD

**Issue by mtw171** [joomlaboat/custom-tables#55]
1. When I upload a csv-file with a date field, the date in the table is one day before the date in the csv-file. Example:

csv-file:
"Name","Email","Adresse","Postleitzahl","Ort","Geburtsdatum","Telefonnummer","QH","MX","MA","AC","AP","RHT","MT","CL","andere"
"Andrea Dom","andrea.dom@xyz.at","Porschestraße 20","1230","Wien","**1960-12-21**","06501234567","Ja","Ja","Ja","Ja","Nein","Ja","Ja","Ja","Ja"

table in database:
Andrea Dom | andrea.dom@xyz.at | Porschestraße 31-33/3/156 | 1230 | Wien | **Dienstag, 20. Dezember 1960** | 06501234567 | Nein | Nein | Nein | Nein | Nein | Nein | Nein | Nein | Nein

2. a string starting in csv-file with + (a european telefon number in international format) ends up in the table starting with _ Example:

csv-file:
"Name","Email","Adresse","Postleitzahl","Ort","Geburtsdatum","Telefonnummer","QH","MX","MA","AC","AP","RHT","MT","CL","andere"
"Andrea Göttin","andrea@goettin.at","Hauptplatz 4","3400","Klosterneuburg","1970-02-02","**+436641234567**","Ja","Ja","Ja","Nein","Nein","Ja","Nein","Nein","Ja"

table in database:
Andrea Göttin | andrea@goettin.at | Hauptplatz 4 | 3400 | Klosterneuburg | Sonntag, 01. Februar 1970 | **_436641234567** | Nein | Nein | Nein | Nein | Nein | Nein | Nein | Nein | Nein

3. when I export data to csv, then a checkbox is represented either with "Ja" or "Nein" (german yes|no). Importing a csv-file with checkboxes ends up in "Nein" even if "Ja" is in the csv-file. Example: both examples above show this

 
**Expected behavior**
the correct date, telefonnumber and checkbox-value should be in the database

**Comment by joomlaboat** [comment]
Hello mtw171,

1. The date problem can be fixed by setting the default Time-Zone in php.ini file:
date.timezone=Europe/Berlin

2. Checking the issue...

**Comment by joomlaboat** [comment]
The plus character issue has been fixed:
v. 3.1.2
https://joomlaboat.com/custom-tables

**Comment by mtw171** [comment]
Solved, thank you!!!
