### ISSUE TITLE
No horizontal scroll bar appears on table page.

### ISSUE THREAD

**Issue by soylera** [joomlaboat/custom-tables#57]
Make a table with 20 columns but can not see right side of table and no horizontal scroll bar appears on the page. How can I add a scroll bar manually under table?

**Comment by joomlaboat** [comment]
Hello Soylera,

The problem is with the template, probably you have a parent div with overflow hidden.

**Comment by soylera** [comment]
How can I fix it with current template. Using this gt-tutorial template from lttheme.com.

https://ltheme.com/project/free-instruction-joomla-template-gt-tutorial/

**Comment by joomlaboat** [comment]
I need to see your website to give some advice.
But you can try this in the Layout:

<div style="width:100%;overflow-x: auto;">
<table> .... </table>
</div>

**Comment by soylera** [comment]
Worked great for table. Thanks a lot.
