### ISSUE TITLE
Changes does not effect in Layout Creator

### ISSUE THREAD

**Issue by soylera** [joomlaboat/custom-tables#58]
On layout creatorpage I use auto create layout function and make some small changes like add edit button or remove delete button etc but changes I made does not have any effect on website. on my first tabel everything works fine ans can see my changes and updates but with my second and third tables bothing changes. I do similar changes on all pages.

**Comment by joomlaboat** [comment]
Hello Soylera,

Please check, maybe the Cache is enabled and or not refreshed.

**Comment by soylera** [comment]
Hi. I cleared Cache still same. I tried from a different device and same result do not see changes.

**Comment by joomlaboat** [comment]
May I see your website?
please contact me via email: support@joomlaboat.com

**Comment by soylera** [comment]
Just send an e-mail. kindly check when you have time please.

**Comment by joomlaboat** [comment]
Thank you.

The Page Layout wasn't selected in the Menu Item, I selected it and it works now.

![image](https://github.com/joomlaboat/custom-tables/assets/8064340/53c7cae6-7a6f-4fec-9f8c-685973e85384)

**Comment by soylera** [comment]
Thank you very much.
