### ISSUE TITLE
Problem creating new field in table

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#59]
When I try te make a new field in an existing table this error message apears:

Field 'asset_id' doesn't have a default value
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'varchar(40) null COMMENT 'Geboorteplaats'' at line 1
Could not save the field.

 - OS: Windows both 10 and 11
 - Browser Firefox 116.0.2
 - Joomla 4.3.4  on php 8.2.8
 - Custom Tables 3.1.4  latest

What can be the course?

**Comment by joomlaboat** [comment]
Hello Menno,

Please delete "asset_id", "params", "version" and "hits" fields. They are not used. They are created by an ancient version of the Custom Tables.

ALTER TABLE `#__customtables_fields`
  DROP `asset_id`,
  DROP `params`,
  DROP `version`,
  DROP `hits`;

**Comment by mennoswaak** [comment]
that helped; it is working now.
I cab add fields and even fill them in the backend
But adding the newly made fields into the layouts is not working.
There is an erros message saying:
0 Typed property CustomTables\Layouts::$layoutId must not be accessed before initialization
please help me with this as well
thanks in advance

**Comment by joomlaboat** [comment]
Please show me a screen-shot where the message appears and/or the file name and the line - in Debug mode.

**Comment by joomlaboat** [comment]
Hello Menno, could you fix the problem? I need to see the error message when it appears.
