### ISSUE TITLE
Twig "if" statement

### ISSUE THREAD

**Issue by froemer4773** [joomlaboat/custom-tables#60]
How to use the Twig if statement in a block? I would like to color a row in a table if a field value contains red, for example

{% if <<field>> = "rot" %}
   <tr class=".rot">
{% else %}
   <tr>
{% endif %}

Field-Name is: {{ category }}

**Comment by joomlaboat** [comment]
Hi froemer4773,

{% if category != "rot" %}
<p>NOT ROT</p>
{% else %} 
<p>ROT</p>
{% endif %}

or 

{% if category.value == "rot" %}
<p>ROT</p>
{% else %} 
<p>NOT ROT</p>
{% endif %}

**Comment by joomlaboat** [comment]
If the category is Table Join field type then: 
{% if category != "rot" %}NOT ROT{% else %}ROT{% endif %}

**Comment by froemer4773** [comment]
> Hi froemer4773,
> 
> {% if category != "rot" %}
> 
> NOT ROT
> 
> {% else %}
> ROT
> 
> {% endif %}
> or
> 
> {% if category.value == "rot" %}
> 
> ROT
> 
> {% else %}
> NOT ROT
> 
> {% endif %}

This is the solution ... greate and THX
