### ISSUE TITLE
field display sum(fields)

### ISSUE THREAD

**Issue by rcr54** [joomlaboat/custom-tables#62]
I want to sum the value of a field over all rows, Like 'select sum(field) from custom.tables.
Is this already possible?

**Comment by joomlaboat** [comment]
**{{ record.sum("products","price","country==germany") }}**

Summarizes values of a selected field of all the records that match the filter.

Parameters

    Table - The name of the Table to count records from.

    Value Field - The field to read the value from.

    Filter - Optional filter, ie. fieldname=some value.
