### ISSUE TITLE
Filter with string not working

### ISSUE THREAD

**Issue by flodi** [joomlaboat/custom-tables#66]
I have set up a menu item to edit a single record of a custom table.

The field to filter is:
3	1	1	cte	CTE		0	0	0	0		3			string	50			0	0			0	

The record I need is:
id	published	es_uc1	es_uc2	es_uc3	es_uc4	es_uc5	es_uc6	es_uc7	es_uc8	es_uc9	es_uc10	es_uc11	es_uc12	es_uc13	es_uc14	es_uc15	es_uc16	es_uc17	es_uc18	es_uc19	es_uc20	es_uc21	es_uc22	es_uc23	es_uc24	es_uc25	es_uc26	es_uc27	es_uc28	es_uc29	es_uc30	es_uc31	es_uc32	es_uc33	es_uc34	es_uc35	es_uc36	es_uc37	es_uc38	es_uc39	es_cte
7	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	roma

In Filter / Search Parameter I put:
cte='roma'

but the menu always create a new record, the menu is this: https://share.cleanshot.com/10KG3K8S+

Thank you

**Comment by joomlaboat** [comment]
Hi, please try cte=roma

**Comment by flodi** [comment]
Unfortunately, same result.

**Comment by joomlaboat** [comment]
I made an update:

https://github.com/joomlaboat/custom-tables

Please try.

**Comment by flodi** [comment]
It works!!! Thank you!!!!!

**Comment by joomlaboat** [comment]
You are welcome.
