### ISSUE TITLE
Field of type File losing content when editing the record

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#68]
Hello 
we have a table with a couple of fields. One is of the type File and ment to upload files.
This is working fine when I create a new record.
But when I edit the record later (changing the content of another field) after Save my File field is empty.'
Is this a bug?

Everything else is working fine.

I'm on Joomla 4.4.1 and php 8.2.7

regards
menno

**Comment by joomlaboat** [comment]
Hello Menno,

It looks like a bug. I will check it.

**Comment by joomlaboat** [comment]
Hello Menno,

Please update to 3.2.0 version. Many many bugs are fixed.
Please try.

**Comment by mennoswaak** [comment]
sorry, but still not working

**Comment by joomlaboat** [comment]
Found the problem. Let you know when fixed.

**Comment by mennoswaak** [comment]
it is fixed, thanks Ivan
