### ISSUE TITLE
File link doesn't work

### ISSUE THREAD

**Issue by CarstenHo** [joomlaboat/custom-tables#72]
Hello!

I created a new field with the function "file link" and selected the folder: /images/fotos.
In the table data, I selected the corresponding photo from the pull-down menu. The field itself is gray in the background.
If I save the data set then the selected photo is not saved and I cannot see an icon or else in the front end.
When I go to the data set again, the selected photo is not there either.

Can you help me?

Thanks!
Carsten

![grafik](https://github.com/joomlaboat/custom-tables/assets/155308924/d6f10391-977c-4eeb-bd6b-58d963b8aa6e)

**Comment by joomlaboat** [comment]
Please download and install an update:

https://github.com/joomlaboat/custom-tables
