### ISSUE TITLE
Search and Reload stopped working

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#75]
I don't know if this happend after the last or an earlier update but in a front end list the Search and the Reload function stopped working.

**Comment by joomlaboat** [comment]
What field type?

**Comment by mennoswaak** [comment]
Table Join  (in de MySQL table it is an integer)
I tried also  Text String (Single Line) and it has the same problem

**Comment by mennoswaak** [comment]
Problem gone.
I suddenly saw in the Joomla System dashboard I had a message that Custom Tables Tables and Custom Layouts were in need of a Check-in.
I did not see it before this evening. I don't know how long these messages were there but after Check-in it is back in normal functioning.
Problem solved

have a nice day

**Comment by joomlaboat** [comment]
Hello Menno,

Glad to hear that.

But Checked-in Tables and Layouts should not affect the front-end search box - something is not right.

**Comment by mennoswaak** [comment]
I have no idea what is wrong.
I just updated to version 3.2.4 and got error messages. So I went back to version 3.2.3 and it is working now.
As I told before we lost after one of the updates a lot of the settings in the Table and Layouts part of 50 or much more Menu Items.
I have to repair them all and actually don't have the time for it. This site should work without to much trouble.
For us there is no choice then stick to version 3.2.3 and make a decision to continue using Custom Tables or move to something else.

**Comment by joomlaboat** [comment]
Updating to version 3.2.4 you need to update the plugin too. It has Loader class renamed, because CTLoader class may be in conflict with other extensions.

Version 3.2.4 does not affect menu items or data saved.

You may uninstall component and the plugin and install again both of them.

**Comment by mennoswaak** [comment]
uninstall and reinstall is within risc to data and settings will be lost?

**Comment by joomlaboat** [comment]
No, but it is always important to have a DB backup.
Uninstall doesn't delete the Database tables.

**Comment by joomlaboat** [comment]
Uninstalling the component will reset Global Configuration - Custom Tables settings, like Google Map API Key:

![image](https://github.com/joomlaboat/custom-tables/assets/8064340/920c3362-1dba-4e57-b1bc-39945d59733f)

**Comment by mennoswaak** [comment]
Load Twig (I think) gave the errors I saw before. It is a conflict with Gantry.
Do not load twig makes everything available again on the frontsite. 
But now Search and Reload is not working.

**Comment by joomlaboat** [comment]
It is a conflict with Gantry. Disable Load Twig in Custom Tables.

RE: But now Search and Reload is not working. - Working on it.

**Comment by mennoswaak** [comment]
Any progress? 
I don't know if this helpes but in CT 3,2,3 it was working

**Comment by joomlaboat** [comment]
I could not find the same result, may I see you website? Or maybe there is JS error message?

**Comment by joomlaboat** [comment]
Maybe you just have to clean the browser cache or force reload the page (CTRL+F5)

**Comment by mennoswaak** [comment]
It is working!
After a few components I needed to update I wanted to start to look for solutions, but ... it was already working.
Maybe there was a conflict that went away after these updates.
It is great that it is working.

But I found another problem:
When in backend I want to Unpublish a record in a Custon Table I get this error message:
"CustomTables\common::inputGetString(): Return value must be of type ?string, array returned "
<html><body>

Call stack
--
# | Function | Location
1 | () | JROOT/components/com_customtables/libraries/ct-common-joomla.php:495
2 | CustomTables\common::inputGetString() | JROOT/components/com_customtables/libraries/customtables/ct/params.php:200
3 | CustomTables\Params->setJoomlaParams() | JROOT/components/com_customtables/libraries/customtables/ct/params.php:137
4 | CustomTables\Params->setParams() | JROOT/components/com_customtables/libraries/customtables/ct/params.php:131
5 | CustomTables\Params->constructJoomlaParams() | JROOT/components/com_customtables/libraries/customtables/ct/params.php:94
6 | CustomTables\Params->__construct() | JROOT/components/com_customtables/libraries/customtables/ct/ct.php:65
7 | CustomTables\CT->__construct() | JROOT/administrator/components/com_customtables/controllers/listofrecords.php:57
8 | CustomtablesControllerListOfRecords->publish() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_customtables/customtables.php:46
10 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
12 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
13 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
14 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
15 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
16 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
17 | require_once() | JROOT/administrator/index.php:32


</body>
</html>

**Comment by joomlaboat** [comment]
Is this issue still exists?

**Comment by joomlaboat** [comment]
The issue "When in backend I want to Unpublish a record in a Custon Table I get this error message"  no longer exists. It has been fixed in the previous updates.
