### ISSUE TITLE
User login to site is presented with landing page error after Custom Tables 3.2.4 update

### ISSUE THREAD

**Issue by dkchick** [joomlaboat/custom-tables#77]
**Describe the bug**
This issue has surfaced after an update to Custom Tables V3.2.4 performed two days ago on 13 Jan.

When registered users log into my site (ccorch.org using 2FA) they are receiving the following message upon submission of the emailed 6-digit confirmation code.

"Call to undefined function 
Joomla\Plugin\Content\CustomTables\Extension\CTLoader()"
**To Reproduce**
1. Registered user logs into the site and submits username and password
2. User submits 2FA 6-digit confirmation code
3. User receives "Call to undefined ........" error message
4. User clicks on "Home" and proceeds normally

**Expected behavior**
User was expected to be viewing the home page instead of the error page

**Screenshots**

**Desktop (please complete the following information):**
-Computer:	Apple silicon Mac Studio
-OS:		macOS Sonoma 14.2.1
-Browsers: 	Chrome Version 120.0.6099.216 (Official Build) (arm64)
		        Safari Version 17.2.1 (19617.1.17.11.12)
-Joomla:	        Version 5.0.2
-Custom Tables:	Version 3.2.4

**Smartphone (please complete the following information):**
 login not yet in use on smart phone

**Additional context**
Perhaps relevant
When Custom Tables was installed and updated the below error message was returned by the Joomla installer.  The install was however also confirmed as successful so the error message has been ignored.

"Update: Could not open update site #33 "Custom Tables - Plugin", URL: update link/extension.xml"
![Screenshot 2024-01-15 at 10 03 39 AM](https://github.com/joomlaboat/custom-tables/assets/50078150/dede8967-34c2-4f1d-a88a-74d9c8302df7)

**Comment by joomlaboat** [comment]
Updating to version 3.2.4 you need to update the Custom Tables Plugin too.

The loader class renamed to CustomTablesLoader, because CTLoader class may be in conflict with other extensions.

Please uninstall the component and the plugin and install them again.

Uninstall doesn't delete the Database tables, but it is always important to have a DB backup.

**Comment by dkchick** [comment]
That fixed it Ivan, Thanks!
