### ISSUE TITLE
Unable to create new records in my table after installing 3.2.4. 

### ISSUE THREAD

**Issue by tooliedotter** [joomlaboat/custom-tables#79]
**Describe the bug**
Unable to create a new record in my table. Clicking New instead opens an existing record. 

**To Reproduce**
1. Go to 'Tables'
2. Click on the numeric marker for that table under Records.
3. Click on New to start a new record for that table. Custom Tables **instead opens an existing record**. 
4. Try making a change to that record and clicking Save. It will save the record. 
5. Try clicking Save and New: it saves the record but does not open a new record. 

**Expected behavior**
Clicking the New button should open a new empty record and allow me to save it. 

**Desktop (please complete the following information):**
- PHP Built On	Linux ip-172-31-61-212 5.10.0-27-cloud-amd64 1 SMP Debian 5.10.205-2 (2023-12-31) x86_64
- Database Type	mysql
- Database Version	10.11.4-MariaDB
- Database Collation	utf8mb4_general_ci
- Database Connection Collation	utf8mb4_general_ci
- Database Connection Encryption	None
- Database Server Supports Connection Encryption	No
- PHP Version	8.1.20
- Web Server	Apache
- WebServer to PHP Interface	fpm-fcgi
- Joomla! Version	Joomla! 4.4.2 Stable [ Pamoja ] 9-January-2024 16:00 GMT
- User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Additional context**
The custom tables worked perfectly BEFORE installing the 3.2.4 update. :-(
I have the Pro version and the Catalog module. 

I am unable to proceed with my project if I cannot add new records.

**Comment by joomlaboat** [comment]
Hello Tooliedotter,

Please try the latest update 3.2.5
https://joomlaboat.com/custom-tables

**Comment by tooliedotter** [comment]
Thank you for the update, that worked! I occasionally bump into a "You do not have permission to directly access that resource" error, but for the most part, things are working. Yay!

**Comment by tooliedotter** [comment]
No, I know better than to do that. It happened when I saved something I think without completing a required field. It happened so fast that I didn't remember how I did it. I did get a screen grab. 
![20240131-cannot-directly-access-that-page](https://github.com/joomlaboat/custom-tables/assets/3389565/5c99299e-9d17-439a-b817-188e6702b4fd)

**Comment by joomlaboat** [comment]
Saving layout or table?

**Comment by tooliedotter** [comment]
I was saving a record, record number 30 in my movies and videos table. But it occurred with other tables prior to your fix.

**Comment by joomlaboat** [comment]
Is that problem still exist, can you repeat it?

**Comment by tooliedotter** [comment]
I cannot regularly repeat it. The only thing I can think of is that I save the record while missing a required field. I recall saving all the other fields but realized I was missing data for one of them. In desperation I saved the record anyway, and it did save the record, but threw this error. Does that help?
