### ISSUE TITLE
HTML button Save & Close only saves but won't close the form

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#81]
In earlier version of CT it used to work but now it works ony partial.
The HTML buttons that are in Layouts like [ Save & Close ] saves the content in the form well but does not close the form to return to the List view. If I add a custom URL then it is working.

I have close to a 100 layouts with probably all the same issue and I'm looking forward to change them all.

Is it possible to go back to the old functionality?

Thanks in advance

**Desktop (please complete the following information):**
 - OS:  Windows 10 and Windows 11
 - Browser Firefox
 - Version 122.0.1

**Comment by joomlaboat** [comment]
Its fixed.

It needed a "return to" parameter.

It happened with Joomla version update.
