### ISSUE TITLE
In auto generated "edit" layout the Go Back option is not visible

### ISSUE THREAD

**Issue by Ranneman** [joomlaboat/custom-tables#82]
**Describe the bug**
In older versions (eg. 3.1.9) of custom tables I have auto generated "edit" pages for table items. In the "edit" window the "go back" option is displayed. Now I'am using version 3.2.6 and the "Go back" option is not visible anymore in the "edit" window.
**To Reproduce**
n.a.

**Expected behavior**
If the auto generated HTML contains the {{ html.goback("Go back") }} tag it must be displayed as it was in the previous versions.

**Screenshots**
old versions showing Go Back
![image](https://github.com/joomlaboat/custom-tables/assets/158061164/1cf1aae0-de88-4cd8-91c8-483db9a29228)
![image](https://github.com/joomlaboat/custom-tables/assets/158061164/c5b562bc-ab5e-4d8a-bb75-acc29a4dd018)

current version 3.2.6 not showing Go back
![image](https://github.com/joomlaboat/custom-tables/assets/158061164/95289f3a-0d1d-41c1-b1d0-ce61dee7c7fb)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser edge
 - Version 121.0.2277.83 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by joomlaboat** [comment]
Thank you [Ranneman](https://github.com/Ranneman)

The issue has been fixed. Please download the update from here - the GitHub.

**Comment by Ranneman** [comment]
Hi,

I have installed this to my local server for testing and the result is okay. However if I ibnstall it to the production server I get an error

Caught exception: An exception has been thrown during the rendering of a template ("Class "ESTables" not found") in "koppelingenEdit" at line 6.

any idea what causes this?

regards Renier


Renier Cilissen
Coördinator Taalontmoetingen

[cid:a4de19be-fdd4-4aa2-85ee-15eb9d08d6d1]

T: +31 6 29357578
E: ***@***.***
W: www.taalontmoetingen.nl
PIW – Taalontmoetingen | Postbus 110 | 6160 AC Geleen

________________________________

**Comment by joomlaboat** [comment]
Hi, uninstall both component and the plugin and install them again. It won't delete the database tables.
