### ISSUE TITLE
Table join not working in add/edit form 

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#84]
**Describe the bug**
In a Add/Edit Form I'm not able to have an editable field.

In layout i have four different approaches:
-----------------------------
<div class="control-group">
<div class="control-label">Voor {{ artikelid.title }} / opleiding nrs.</div><div class="controls">{{ artikelid.edit("","",[],"MyCursusTitle","","virtualselect") }}</div>
	</div>  
  
<div class="control-group">
<div class="control-label">Voor {{ artikelid.title }} / opleiding nr.</div><div class="controls">{{ artikelid.layout("MyCursusTitle") }}</div>
	</div> 
  
<div class="control-group">
<div class="control-label">Voor {{ artikelid.title }} / opleiding nr.</div><div class="controls">{{ artikelid.edit }}</div>
	</div> 
  
<div class="control-group">
<div class="control-label">Voor {{ artikelid.title }} / opleiding nr.</div><div class="controls">{{ artikelid }}</div>
	</div> 
-----------------------------------------
In the front this results in:
---------------------------------------
Voor Cursus / opleiding nrs.
Table Join child not found.

Voor Cursus / opleiding nr.
594 - Voedselbosrand 2022 3

Voor Cursus / opleiding nr.
Table Join child not found.

Voor Cursus / opleiding nr.
594
--------------------------------------
As you can see: the two artikelid.edit fiels give "Table Join child not found"
But the other two work well.

I'm afraid it is a bug
or do you have a solution?

Thanks in advance
menno

**Comment by joomlaboat** [comment]
found where the problem is. working on it.

**Comment by domath2k** [comment]
None of my table joins are working as of the latest version.
![image](https://github.com/joomlaboat/custom-tables/assets/155865425/6813db3f-ef88-43e2-a25e-5ee504fb5a37)

**Comment by joomlaboat** [comment]
Hello Menno,

I fixed the Table Join Input box problem.

Please download and install both Component and the Pro plugin.

Regards,
Ivan

**Comment by mennoswaak** [comment]
That is great Ivan but he download link for the Pro version in not working and giving a 404 message

**Comment by joomlaboat** [comment]
I see. it adds extra host name. sorry for that. going to fix it asap

**Comment by domath2k** [comment]
Thanks. The new version fixed the joins for me.

**Comment by mennoswaak** [comment]
hope it will be available soon, thanks

**Comment by domath2k** [comment]
@mennoswaak 
> hope it will be available soon, thanks

Just manually remove the extra host name in the url until Ivan gets a chance to fix it. 
Like this, it works fine;

![image](https://github.com/joomlaboat/custom-tables/assets/155865425/b8cb44c0-a4ca-4d82-91bc-05bfb72a3160)

**Comment by joomlaboat** [comment]
Fixed.

**Comment by mennoswaak** [comment]
Thnaks, it is working now
