### ISSUE TITLE
Error creating a menu entry

### ISSUE THREAD

**Issue by CyrisID** [joomlaboat/custom-tables#85]
**Describe the bug**
After successfully installing the plugin, I attempted to create a menu entry. Unfortunately, this failed with an error. Testing on a separate, second Joomla installation yielded the same result.

**To Reproduce**
1. Go to the Administrator Control Panel
2. Click on the left side on Menu, then on Main Menu
3. Click Add (top Left)
4. Chose Custom Tables an then "Add/Edit Record"
5. See error: _An error has occurred. 0 Undefined constant "CUSTOMTABLES_LIBRARIES_PATH"_

**Screenshots**
![JoomlaError](https://github.com/joomlaboat/custom-tables/assets/83970120/ca29cf6c-9aef-44fb-84b1-3f88e495f1cf)

**Desktop (please complete the following information):**
Database Type mysql
Database Version 11.1.2-MariaDB
Database Collation utf8mb4_general_ci
Database Connection Collation utf8mb4_general_ci
Database Connection Encryption None
Database Server Supports Connection Encryption No
PHP Version 8.2.12
Web Server Microsoft-IIS/10.0
Joomla! 4.4.3 Stable [ Pamoja ] 20-February-2024 16:00 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Additional context**

**Comment by jsmoothsalsa** [comment]
Hi I have the same problem also. Just installed to test this out on 3/29/24 with same results.

**Comment by joomlaboat** [comment]
Hello everyone.

Its fixed. Please download the update from the git hub:

https://github.com/joomlaboat/custom-tables

**Comment by jsmoothsalsa** [comment]
Symfony\Component\ErrorHandler\Error\FatalError thrown with message "Compile Error: Declaration of Gantry\Component\Twig\TwigExtension::getGlobals() must be compatible with Twig\Extension\GlobalsInterface::getGlobals(): array"

Stacktrace:
#0 Symfony\Component\ErrorHandler\Error\FatalError in /home2/hellobac/public_html/libraries/gantry5/src/classes/Gantry/Component/Twig/TwigExtension.php:53
![3-1-2024 11-28-24 AM](https://github.com/joomlaboat/custom-tables/assets/161873227/435ccac8-ec9f-4754-a80b-c69615e389a2)

**Comment by joomlaboat** [comment]
There is a conflict with the Gantry template.

Please disable Twig Load.

![image](https://github.com/joomlaboat/custom-tables/assets/8064340/0d42c755-68e8-434f-8b3e-7b76c6950ae6)

**Comment by jsmoothsalsa** [comment]
Resolved thank you very much for your help.

**Comment by joomlaboat** [comment]
Glad to hear that. You are welcome.
