### ISSUE TITLE
Custom Tables Catalog Module  error

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#87]
And think it is since the last update Custom Tables Catalog Module is gicing this error message:

CustomTables\CT::__construct(): Argument #1 ($menuParams) must be of type ?array, Joomla\Registry\Registry given, called in /home/permacultuurnet/permacultuur.net/modules/mod_ctcatalog/mod_ctcatalog.php on line 23

And then al lot more. I think the most important code lines are the first: 
in[ /home/permacultuurnet/permacultuur.net/components/com_customtables/libraries/customtables/ct/ct.php ](https://permacultuur.net/index.php/taco/deelnemers-taco?view=catalog)(line 47)

43        //Joomla Specific
44       var $app;
45        var $document;
46
47        function __construct(?array $menuParams = null, $blockExternalVars = true, ?string $ModuleId = null, bool $enablePlugin = true)
48        {
49            $this->errors = [];
50            $this->messages = [];
51
52           if (defined('_JEXEC')) { 

All pages where the CT module is at the side don't open but give only these error messages.

can you do something about it?

This is on Joomla 4.4.3

**Comment by joomlaboat** [comment]
Hello Menno, please the latest component, module, or plugin.

**Comment by mennoswaak** [comment]
Thanks Ivan, but the module still gives the same error message

**Comment by mennoswaak** [comment]
is there a workaround that I can use myself to solve this problem?

**Comment by joomlaboat** [comment]
Hello Menno,

Fixed the problem. Please download the Custom Tables Catalog Module update 3.2.9 from the website.

https://joomlaboat.com/my-downloads
