### ISSUE TITLE
Access to images by link

### ISSUE THREAD

**Issue by Mario-Broz** [joomlaboat/custom-tables#89]
Hello Joomlaboat,
I'm using the free version of TableMaker 3.2.8. 
I have a custom table with a field having 'File Link' type.
When I enter new data for this field, I access the mysite/images/subdirectory which contains the image files, however I have a 404 error on the simple catalog layout because the link now points to mysite/subdirectory. 
The only way I found to get around the problem is to change the path directly in the customtables_fields table.

**Comment by joomlaboat** [comment]
Hello Mario-Broz,

Please try to download an update from the GitHub.

**Comment by joomlaboat** [comment]
There was a problem with Linux, please try the update (not from the website)

**Comment by Mario-Broz** [comment]
Works fine. Thank you.
