### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#91]
This afternoon I updated Custom Tables, Pro and the Modules to the newest version.
At the frontend I now get a Compile Error. It looks like it comes from Gantry and a Twig extension.
It comes with much more messages but the site is not available.

So I disabled the Custom Tables Plugin and the site is available again.
Strangely enough: my Custom Tables, detail pages and edit forms are working as they should.

What is happening?

regards
Menno

**Comment by joomlaboat** [comment]
Hello Menno,

Disable Twig Loading in Global Configuration / Custom Tables

**Comment by mennoswaak** [comment]
Hello Ivan

that was already my setting

**Comment by joomlaboat** [comment]
Can you please make a screen-shot with the error message?

**Comment by mennoswaak** [comment]
So I had to disable the plugin and then when I visit the site at the frontend these 2 messages at the left (schermafdruk-1.jpg) 
![Schermafdruk-1](https://github.com/joomlaboat/custom-tables/assets/102488514/4846ba84-5066-4ce3-89ea-e1ec361e2094)
and a bigger one at the right (schermafdruk-2.jpg)
![Schermafdruk-2](https://github.com/joomlaboat/custom-tables/assets/102488514/5e155182-df82-4e38-b53e-59623a416df1)
And beneath that there is more information on Environment & details

**Comment by joomlaboat** [comment]
I think I know where is the problem. Please uninstall Custom Tables Plugin and download/install again.

Old plugin used Joomla 3 file structure and the new one Joomla 4 MVC, installing new plugin over the old left an old file there, and the old file didn't read Global Configuration params.

**Comment by mennoswaak** [comment]
After reinstalling, the problem is the same. 
The strange thing that everything works fine when the plugin is disabled. All tables and forms included. How can that be?

**Comment by joomlaboat** [comment]
Can you show what files are in /plugin/content/customtables folder?

**Comment by mennoswaak** [comment]
customtables.xml
index.html
**inputbox:**
tablejoin.php
tablejoinlist.php
**js:**
chart.js
jquery.uploadfile.js
raphael.js
raphael.min.js
**protagprocessor**
customphp.php
helpers.php
index.html
phptags.php
servertags.php
**services**
provider.php
**src**
- **Extension**
- customtables.php

**Comment by joomlaboat** [comment]
file: src/Extension/customtables.php

please try to change the line 69 to

$loadTwig = false;//$params->get('loadTwig') ?? true;

I suspect that it cannot read the configuration value.

I tried to repeat the same situation on my localhost and nothing. No errors.

**Comment by mennoswaak** [comment]
on line 69 I see only a  }  
Is that what you want me to replace?

**Comment by joomlaboat** [comment]
It looks like the Custom Tables Plugin is not updated on your website.

![image](https://github.com/joomlaboat/custom-tables/assets/8064340/f8c61dc0-e620-4d6f-aa6f-5d6b209b86a0)

**Comment by mennoswaak** [comment]
The date of the file showed it was updated. 
So I did another update and now it is working well
thanks

**Comment by joomlaboat** [comment]
Glad to hear that.
