### ISSUE TITLE
Field 'params' doesn't have a default value & update mess

### ISSUE THREAD

**Issue by Mario-Broz** [joomlaboat/custom-tables#95]
Hello Joomlaboat
I'm using the free version of Custom tables.
I wanted to create a new layout but I got an error message "The 'params' field has no default value". 
When trying to modify an existing layout, I got the same error message. 
Then I saw that I was in v3.3.3 and that the latest version was v3.3.6. So I decided to install it. And there the drama!. 
I have a green message saying that the installation is done, a yellow one that tells me "construction error in the administration menus" and a red one that tells me "Field 'id' doesn't have a default value". Result: the frontend still seems to work correctly, but I have nothing left in the backend.
![Capture d'écran 2024-07-29 195028](https://github.com/user-attachments/assets/34632ad6-0a96-462a-92ea-0e63186b62f3)

Any idea ?

Regards
Mario

**Comment by joomlaboat** [comment]
Hello Mario,

Please delete column "params" in #__customtables_layouts table

Also id fields needs to have autoincrement attribute.

Regards,
Ivan

**Comment by Mario-Broz** [comment]
Hello Ivan,
unfortunately it didn't work.
I deleted the 'params' field and all the 'id' are autoincrement.
I compared the #_customtables_layouts table with the one from a 'clean' direct installation in v3.3.6 and to my surprise I have 4 additional fields; 'asset_id', 'version', 'hits' and 'ordering' in my v3.3.3
I guess a previous update went wrong.
I think I'll uninstall the component and then install v3.3.6 from scratch and import the data into my #_customtables_table_#

Regards,
Mario

**Comment by joomlaboat** [comment]
Hello Mario,

Uninstalling the component won't delete database tables. Delete theme
manually or delete these old unused fields.

Regards,
Ivan

**Comment by Mario-Broz** [comment]
Hello Ivan,
In the end I deleted the unnecessary fields in the #_customtables_layouts table as well as a few obsolete fields in my data table, then I did the update.
Everything works fine now!

Thanks a lot

Regards,
Mario

**Comment by joomlaboat** [comment]
Glad to hear it!
Regards,
Ivan
